### ISSUE TITLE
Torch 12+

### ISSUE THREAD

**Issue by brucethemoose** [ogkalu2/Merge-Stable-Diffusion-models-without-distortion#22]
What is blocking higher versions of pytorch from being used?

Also this is a very interesting implementation. Gonna test it out, and I hope it gets merged into other repos, given all the interest in merging :+1:

**Comment by ogkalu2** [comment]
Pytorch removed cpu support for some operations in 1.12

**Comment by brucethemoose** [comment]
My merges seem to work well.

:+1: Hope it can get worked around eventually, as thats kinda a blocker for pulling this into bigger projects.
