### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by s1dlx** [ogkalu2/Merge-Stable-Diffusion-models-without-distortion#37]
hello!

I'd like to add re-basin to [meh](https://github.com/s1dlx/meh) so that I can then use it with the [bayesian-merger](https://github.com/s1dlx/sd-webui-bayesian-merger). In these regards:

- is there any license attached to this repo?
- are you planning to release it as a package on pypi for other to use it?

thanks!

**Comment by ogkalu2** [comment]
- Just added a license (MIT)
- wasn't planning the second
