### ISSUE TITLE
RuntimeError: expected scalar type Float but found Half

### ISSUE THREAD

**Issue by thojmr** [ogkalu2/Merge-Stable-Diffusion-models-without-distortion#5]
Hey there, trying out this merge implementation for the first time but running this consistent issue.  Seems to happen for many different combinations of model merges.  Both novel based and sd-v1-4 based models.

I should also mention that I am using the "device id" pull request https://github.com/ogkalu2/Merge-Stable-Diffusion-models-without-distortion/pull/4, but even without that I get the same error.

```
Traceback (most recent call last):
  File "SD_rebasin_merge.py", line 23, in <module>
    final_permutation = weight_matching(permutation_spec, state_a, state_b, device)
  File "/mnt/c/Users/<redacted>/ML/apps/merge-stable-diffusion-models-without-distortion/weight_matching.py", line 800, in weight_matching
    A += w_a @ w_b.T
RuntimeError: expected scalar type Float but found Half
```

**Comment by IdiotSandwichTheThird** [comment]
You have to download the 32bit models.

**Comment by thojmr** [comment]
Makes sense. It would be nice if it would just autocast to 32bit.  Everyone that uses this script is going to run into the same problem.

**Comment by thojmr** [comment]
Promising results so far, seems to preserve dreambooth concepts better than a normal 50/50 merge does with `dreambooth > f222` merge

**Comment by thojmr** [comment]
Latest merge #7 should have fixed this
