### ISSUE TITLE
Bias toward model b 

### ISSUE THREAD

**Issue by vaguenebula** [ogkalu2/Merge-Stable-Diffusion-models-without-distortion#8]
I thought i would make a separate issue for this to keep things organized. So i figured some stuff out. In the original code, the authors apply the permutation after making the final permutation. Here is what I changed in my fork:
![image](https://user-images.githubusercontent.com/65990273/203147382-3ee75453-2f6b-4e06-886c-d1ee0b0c9a2f.png)

This does give a different model thats not biased. However, the resultant image is blue. I have no idea why.
![image](https://user-images.githubusercontent.com/65990273/203147631-b9b729f1-4161-4062-b892-c67fa50f43b1.png)
![image](https://user-images.githubusercontent.com/65990273/203147664-1fc475c2-d33d-4bc6-8b6b-ea8449ad6d2a.png)

So this is progress. But i think the reason its not working is because i skipped some big layers, so I will try experimenting and seeing if I can get this to work.

**Comment by vaguenebula** [comment]
Just realized

**Comment by vaguenebula** [comment]
im still getting blue images, so it seems that applying the permutation in this manner gives a different result

**Comment by ogkalu2** [comment]
@vaguenebula I also apply the permutation after the weight matching. The code after final_permutation in my code is basically manually applying the apply permutation function. I used the function before nbut changed it manually to see of there was anything up with the function itself. What exactly are you saving in torch.save ? updated_params ?

**Comment by vaguenebula** [comment]
> @vaguenebula I also apply the permutation after the weight matching. The code after final_permutation in my code is basically manually applying the apply permutation function. I used the function before nbut changed it manually to see of there was anything up with the function itself. What exactly are you saving in torch.save ? updated_params ?

For some reason, its giving me a good result. i will submit pull request so you can experiment with the code

**Comment by vaguenebula** [comment]
> @vaguenebula I also apply the permutation after the weight matching. The code after final_permutation in my code is basically manually applying the apply permutation function. I used the function before nbut changed it manually to see of there was anything up with the function itself. What exactly are you saving in torch.save ? updated_params ?

i fixed the blue image now. .its a mix of two models

**Comment by vaguenebula** [comment]
> @vaguenebula I also apply the permutation after the weight matching. The code after final_permutation in my code is basically manually applying the apply permutation function. I used the function before nbut changed it manually to see of there was anything up with the function itself. What exactly are you saving in torch.save ? updated_params ?

it might just be the wrong implementation of the method somehow. im not sure

**Comment by vaguenebula** [comment]
wait whhhatt im getting model a back now
